"""
anime_catalog.json に新規50作品を追加するスクリプト。
対象: 2015-2024年の人気作品（既存50作品と重複しないもの）
"""
import json
from pathlib import Path

CATALOG_PATH = Path(__file__).parent / "anime_catalog.json"

NEW_ANIME = [
    # ── 2015 ──────────────────────────────────────────────────────────────────
    {
        "anime_title": "one_punch_man",
        "anime_title_ja": "ワンパンマン",
        "wikipedia_page_title": "ワンパンマン (テレビアニメ)",
        "gt_query": "ワンパンマン アニメ",
        "air_start": "2015-10-04",
        "air_end": "2015-12-20",
        "total_episodes": 12,
        "popularity_tier": "high",
    },
    # ── 2016 ──────────────────────────────────────────────────────────────────
    {
        "anime_title": "konosuba_s1",
        "anime_title_ja": "この素晴らしい世界に祝福を！",
        "wikipedia_page_title": "この素晴らしい世界に祝福を!",
        "gt_query": "このすば アニメ",
        "air_start": "2016-01-14",
        "air_end": "2016-03-30",
        "total_episodes": 10,
        "popularity_tier": "high",
    },
    {
        "anime_title": "re_zero_s1",
        "anime_title_ja": "Re:ゼロから始める異世界生活",
        "wikipedia_page_title": "Re:ゼロから始める異世界生活 (アニメ)",
        "gt_query": "リゼロ アニメ",
        "air_start": "2016-04-04",
        "air_end": "2016-09-19",
        "total_episodes": 25,
        "popularity_tier": "high",
    },
    {
        "anime_title": "my_hero_academia_s1",
        "anime_title_ja": "僕のヒーローアカデミア 第1期",
        "wikipedia_page_title": "僕のヒーローアカデミア (アニメ)",
        "gt_query": "ヒロアカ アニメ",
        "air_start": "2016-04-03",
        "air_end": "2016-06-26",
        "total_episodes": 13,
        "popularity_tier": "high",
    },
    {
        "anime_title": "mob_psycho_100",
        "anime_title_ja": "モブサイコ100",
        "wikipedia_page_title": "モブサイコ100 (アニメ)",
        "gt_query": "モブサイコ100 アニメ",
        "air_start": "2016-07-12",
        "air_end": "2016-09-27",
        "total_episodes": 12,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "yuri_on_ice",
        "anime_title_ja": "ユーリ!!! on ICE",
        "wikipedia_page_title": "ユーリ!!! on ICE",
        "gt_query": "ユーリオンアイス アニメ",
        "air_start": "2016-10-06",
        "air_end": "2016-12-22",
        "total_episodes": 12,
        "popularity_tier": "high",
    },
    # ── 2017 ──────────────────────────────────────────────────────────────────
    {
        "anime_title": "konosuba_s2",
        "anime_title_ja": "この素晴らしい世界に祝福を！2",
        "wikipedia_page_title": "この素晴らしい世界に祝福を!2",
        "gt_query": "このすば2 アニメ",
        "air_start": "2017-01-12",
        "air_end": "2017-03-16",
        "total_episodes": 10,
        "popularity_tier": "high",
    },
    {
        "anime_title": "youjo_senki",
        "anime_title_ja": "幼女戦記",
        "wikipedia_page_title": "幼女戦記 (アニメ)",
        "gt_query": "幼女戦記 アニメ",
        "air_start": "2017-01-06",
        "air_end": "2017-03-31",
        "total_episodes": 12,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "my_hero_academia_s2",
        "anime_title_ja": "僕のヒーローアカデミア 第2期",
        "wikipedia_page_title": "僕のヒーローアカデミア (アニメ)",
        "gt_query": "ヒロアカ 2期",
        "air_start": "2017-04-01",
        "air_end": "2017-09-30",
        "total_episodes": 25,
        "popularity_tier": "high",
    },
    {
        "anime_title": "attack_on_titan_s2",
        "anime_title_ja": "進撃の巨人 第2期",
        "wikipedia_page_title": "進撃の巨人 (アニメ)",
        "gt_query": "進撃の巨人 2期",
        "air_start": "2017-04-01",
        "air_end": "2017-06-17",
        "total_episodes": 12,
        "popularity_tier": "high",
    },
    {
        "anime_title": "made_in_abyss",
        "anime_title_ja": "メイドインアビス",
        "wikipedia_page_title": "メイドインアビス (アニメ)",
        "gt_query": "メイドインアビス アニメ",
        "air_start": "2017-07-07",
        "air_end": "2017-09-29",
        "total_episodes": 13,
        "popularity_tier": "high",
    },
    # ── 2018 ──────────────────────────────────────────────────────────────────
    {
        "anime_title": "my_hero_academia_s3",
        "anime_title_ja": "僕のヒーローアカデミア 第3期",
        "wikipedia_page_title": "僕のヒーローアカデミア (アニメ)",
        "gt_query": "ヒロアカ 3期",
        "air_start": "2018-04-07",
        "air_end": "2018-09-29",
        "total_episodes": 25,
        "popularity_tier": "high",
    },
    {
        "anime_title": "hataraku_saibou",
        "anime_title_ja": "はたらく細胞",
        "wikipedia_page_title": "はたらく細胞 (アニメ)",
        "gt_query": "はたらく細胞 アニメ",
        "air_start": "2018-07-07",
        "air_end": "2018-09-29",
        "total_episodes": 13,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "attack_on_titan_s3",
        "anime_title_ja": "進撃の巨人 第3期",
        "wikipedia_page_title": "進撃の巨人 (アニメ)",
        "gt_query": "進撃の巨人 3期",
        "air_start": "2018-07-23",
        "air_end": "2018-10-15",
        "total_episodes": 12,
        "popularity_tier": "high",
    },
    {
        "anime_title": "goblin_slayer",
        "anime_title_ja": "ゴブリンスレイヤー",
        "wikipedia_page_title": "ゴブリンスレイヤー (アニメ)",
        "gt_query": "ゴブリンスレイヤー アニメ",
        "air_start": "2018-10-07",
        "air_end": "2018-12-30",
        "total_episodes": 12,
        "popularity_tier": "medium",
    },
    # ── 2019 ──────────────────────────────────────────────────────────────────
    {
        "anime_title": "tate_no_yuusha",
        "anime_title_ja": "盾の勇者の成り上がり",
        "wikipedia_page_title": "盾の勇者の成り上がり (アニメ)",
        "gt_query": "盾の勇者 アニメ",
        "air_start": "2019-01-09",
        "air_end": "2019-06-26",
        "total_episodes": 25,
        "popularity_tier": "high",
    },
    {
        "anime_title": "attack_on_titan_s3p2",
        "anime_title_ja": "進撃の巨人 第3期 Part2",
        "wikipedia_page_title": "進撃の巨人 (アニメ)",
        "gt_query": "進撃の巨人 3期 Part2",
        "air_start": "2019-04-29",
        "air_end": "2019-07-01",
        "total_episodes": 10,
        "popularity_tier": "high",
    },
    {
        "anime_title": "fruits_basket_2019",
        "anime_title_ja": "フルーツバスケット（2019年）",
        "wikipedia_page_title": "フルーツバスケット (2019年のアニメ)",
        "gt_query": "フルーツバスケット 2019",
        "air_start": "2019-04-06",
        "air_end": "2019-09-21",
        "total_episodes": 25,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "fire_force",
        "anime_title_ja": "炎炎ノ消防隊",
        "wikipedia_page_title": "炎炎ノ消防隊 (アニメ)",
        "gt_query": "炎炎ノ消防隊 アニメ",
        "air_start": "2019-07-06",
        "air_end": "2019-12-28",
        "total_episodes": 24,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "cautious_hero",
        "anime_title_ja": "慎重勇者〜この勇者が俺TUEEEくせに慎重すぎる〜",
        "wikipedia_page_title": "慎重勇者〜この勇者が俺TUEEEくせに慎重すぎる〜",
        "gt_query": "慎重勇者 アニメ",
        "air_start": "2019-10-02",
        "air_end": "2019-12-25",
        "total_episodes": 12,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "one_punch_man_s2",
        "anime_title_ja": "ワンパンマン 第2期",
        "wikipedia_page_title": "ワンパンマン (テレビアニメ)",
        "gt_query": "ワンパンマン 2期",
        "air_start": "2019-04-09",
        "air_end": "2019-07-02",
        "total_episodes": 12,
        "popularity_tier": "high",
    },
    {
        "anime_title": "my_hero_academia_s4",
        "anime_title_ja": "僕のヒーローアカデミア 第4期",
        "wikipedia_page_title": "僕のヒーローアカデミア (アニメ)",
        "gt_query": "ヒロアカ 4期",
        "air_start": "2019-10-12",
        "air_end": "2020-04-04",
        "total_episodes": 25,
        "popularity_tier": "high",
    },
    # ── 2020 ──────────────────────────────────────────────────────────────────
    {
        "anime_title": "eizouken",
        "anime_title_ja": "映像研には手を出すな！",
        "wikipedia_page_title": "映像研には手を出すな!",
        "gt_query": "映像研 アニメ",
        "air_start": "2020-01-05",
        "air_end": "2020-03-22",
        "total_episodes": 12,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "hamefura",
        "anime_title_ja": "乙女ゲームの破滅フラグしかない悪役令嬢に転生してしまった",
        "wikipedia_page_title": "乙女ゲームの破滅フラグしかない悪役令嬢に転生してしまった (アニメ)",
        "gt_query": "はめふら アニメ",
        "air_start": "2020-04-04",
        "air_end": "2020-06-27",
        "total_episodes": 12,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "tower_of_god",
        "anime_title_ja": "神之塔 -Tower of God-",
        "wikipedia_page_title": "神之塔 -Tower of God-",
        "gt_query": "タワーオブゴッド アニメ",
        "air_start": "2020-04-02",
        "air_end": "2020-06-25",
        "total_episodes": 13,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "deca_dence",
        "anime_title_ja": "デカダンス",
        "wikipedia_page_title": "デカダンス",
        "gt_query": "デカダンス アニメ",
        "air_start": "2020-07-09",
        "air_end": "2020-09-24",
        "total_episodes": 12,
        "popularity_tier": "low",
    },
    {
        "anime_title": "haikyuu_s4p2",
        "anime_title_ja": "ハイキュー!! TO THE TOP 第2クール",
        "wikipedia_page_title": "ハイキュー!! TO THE TOP",
        "gt_query": "ハイキュー TO THE TOP",
        "air_start": "2020-10-03",
        "air_end": "2020-12-19",
        "total_episodes": 13,
        "popularity_tier": "high",
    },
    # ── 2021 ──────────────────────────────────────────────────────────────────
    {
        "anime_title": "my_hero_academia_s5",
        "anime_title_ja": "僕のヒーローアカデミア 第5期",
        "wikipedia_page_title": "僕のヒーローアカデミア (アニメ)",
        "gt_query": "ヒロアカ 5期",
        "air_start": "2021-03-27",
        "air_end": "2021-09-25",
        "total_episodes": 25,
        "popularity_tier": "high",
    },
    {
        "anime_title": "ijiranaide_nagatoro",
        "anime_title_ja": "いじらないで、長瀞さん",
        "wikipedia_page_title": "いじらないで、長瀞さん (アニメ)",
        "gt_query": "長瀞さん アニメ",
        "air_start": "2021-04-11",
        "air_end": "2021-06-27",
        "total_episodes": 12,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "fumetsu_no_anata_e",
        "anime_title_ja": "不滅のあなたへ",
        "wikipedia_page_title": "不滅のあなたへ (アニメ)",
        "gt_query": "不滅のあなたへ アニメ",
        "air_start": "2021-04-12",
        "air_end": "2021-09-27",
        "total_episodes": 20,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "mieruko_chan",
        "anime_title_ja": "見える子ちゃん",
        "wikipedia_page_title": "見える子ちゃん (アニメ)",
        "gt_query": "見える子ちゃん アニメ",
        "air_start": "2021-10-03",
        "air_end": "2021-12-19",
        "total_episodes": 12,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "blue_period",
        "anime_title_ja": "ブルーピリオド",
        "wikipedia_page_title": "ブルーピリオド (アニメ)",
        "gt_query": "ブルーピリオド アニメ",
        "air_start": "2021-10-01",
        "air_end": "2021-12-17",
        "total_episodes": 12,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "komi_san",
        "anime_title_ja": "古見さんはコミュ症です",
        "wikipedia_page_title": "古見さんはコミュ症です (アニメ)",
        "gt_query": "古見さん アニメ",
        "air_start": "2021-10-07",
        "air_end": "2021-12-29",
        "total_episodes": 12,
        "popularity_tier": "medium",
    },
    # ── 2022 ──────────────────────────────────────────────────────────────────
    {
        "anime_title": "ao_ashi",
        "anime_title_ja": "アオアシ",
        "wikipedia_page_title": "アオアシ (アニメ)",
        "gt_query": "アオアシ アニメ",
        "air_start": "2022-04-09",
        "air_end": "2022-09-24",
        "total_episodes": 24,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "isekai_ojisan",
        "anime_title_ja": "異世界おじさん",
        "wikipedia_page_title": "異世界おじさん (アニメ)",
        "gt_query": "異世界おじさん アニメ",
        "air_start": "2022-07-06",
        "air_end": "2022-12-28",
        "total_episodes": 13,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "spy_x_family_part2",
        "anime_title_ja": "SPY×FAMILY Part 2",
        "wikipedia_page_title": "SPY×FAMILY (アニメ)",
        "gt_query": "スパイファミリー Part2",
        "air_start": "2022-10-01",
        "air_end": "2022-12-24",
        "total_episodes": 13,
        "popularity_tier": "high",
    },
    {
        "anime_title": "mob_psycho_100_s3",
        "anime_title_ja": "モブサイコ100 III",
        "wikipedia_page_title": "モブサイコ100 (アニメ)",
        "gt_query": "モブサイコ100 III",
        "air_start": "2022-10-05",
        "air_end": "2022-12-28",
        "total_episodes": 12,
        "popularity_tier": "high",
    },
    {
        "anime_title": "kage_no_jitsuryokusha",
        "anime_title_ja": "陰の実力者になりたくて！",
        "wikipedia_page_title": "陰の実力者になりたくて! (アニメ)",
        "gt_query": "陰実 アニメ",
        "air_start": "2022-10-05",
        "air_end": "2023-03-22",
        "total_episodes": 20,
        "popularity_tier": "high",
    },
    # ── 2023 ──────────────────────────────────────────────────────────────────
    {
        "anime_title": "tomo_chan_wa_onnanoko",
        "anime_title_ja": "トモちゃんは女の子！",
        "wikipedia_page_title": "トモちゃんは女の子! (アニメ)",
        "gt_query": "トモちゃん アニメ",
        "air_start": "2023-01-05",
        "air_end": "2023-03-23",
        "total_episodes": 13,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "vinland_saga_s2",
        "anime_title_ja": "ヴィンランド・サガ SEASON 2",
        "wikipedia_page_title": "ヴィンランド・サガ (アニメ)",
        "gt_query": "ヴィンランドサガ Season2",
        "air_start": "2023-01-10",
        "air_end": "2023-07-04",
        "total_episodes": 24,
        "popularity_tier": "high",
    },
    {
        "anime_title": "dr_stone_new_world",
        "anime_title_ja": "Dr.STONE NEW WORLD",
        "wikipedia_page_title": "Dr.STONE (アニメ)",
        "gt_query": "Dr.STONE NEW WORLD",
        "air_start": "2023-04-06",
        "air_end": "2023-06-15",
        "total_episodes": 11,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "mahou_tsukai_no_yome_s2",
        "anime_title_ja": "魔法使いの嫁 SEASON 2",
        "wikipedia_page_title": "魔法使いの嫁 (テレビアニメ第2シリーズ)",
        "gt_query": "魔法使いの嫁 Season2",
        "air_start": "2023-04-07",
        "air_end": "2023-09-22",
        "total_episodes": 24,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "bleach_tybw_p2",
        "anime_title_ja": "BLEACH 千年血戦篇-訣別譚-",
        "wikipedia_page_title": "BLEACH (アニメ)",
        "gt_query": "ブリーチ 千年血戦篇",
        "air_start": "2023-07-08",
        "air_end": "2023-12-30",
        "total_episodes": 13,
        "popularity_tier": "high",
    },
    {
        "anime_title": "kusuriya_no_hitorigoto",
        "anime_title_ja": "薬屋のひとりごと",
        "wikipedia_page_title": "薬屋のひとりごと (アニメ)",
        "gt_query": "薬屋のひとりごと アニメ",
        "air_start": "2023-10-22",
        "air_end": "2024-03-24",
        "total_episodes": 24,
        "popularity_tier": "high",
    },
    {
        "anime_title": "undead_unluck",
        "anime_title_ja": "アンデッドアンラック",
        "wikipedia_page_title": "アンデッドアンラック (アニメ)",
        "gt_query": "アンデッドアンラック アニメ",
        "air_start": "2023-10-07",
        "air_end": "2024-03-30",
        "total_episodes": 24,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "shangri_la_frontier",
        "anime_title_ja": "シャングリラ・フロンティア",
        "wikipedia_page_title": "シャングリラ・フロンティア (アニメ)",
        "gt_query": "シャングリラフロンティア アニメ",
        "air_start": "2023-10-01",
        "air_end": "2024-03-24",
        "total_episodes": 25,
        "popularity_tier": "high",
    },
    # ── 2024 ──────────────────────────────────────────────────────────────────
    {
        "anime_title": "dungeon_meshi",
        "anime_title_ja": "ダンジョン飯",
        "wikipedia_page_title": "ダンジョン飯 (アニメ)",
        "gt_query": "ダンジョン飯 アニメ",
        "air_start": "2024-01-04",
        "air_end": "2024-06-28",
        "total_episodes": 24,
        "popularity_tier": "high",
    },
    {
        "anime_title": "boku_yaba_s2",
        "anime_title_ja": "僕の心のヤバイやつ Season 2",
        "wikipedia_page_title": "僕の心のヤバイやつ (アニメ)",
        "gt_query": "僕ヤバ Season2",
        "air_start": "2024-01-07",
        "air_end": "2024-03-31",
        "total_episodes": 13,
        "popularity_tier": "medium",
    },
    {
        "anime_title": "konosuba_s3",
        "anime_title_ja": "この素晴らしい世界に祝福を！3",
        "wikipedia_page_title": "この素晴らしい世界に祝福を!3",
        "gt_query": "このすば3 アニメ",
        "air_start": "2024-04-10",
        "air_end": "2024-06-19",
        "total_episodes": 11,
        "popularity_tier": "high",
    },
    {
        "anime_title": "kimetsu_hashira_geiko",
        "anime_title_ja": "鬼滅の刃 柱稽古編",
        "wikipedia_page_title": "鬼滅の刃 柱稽古編",
        "gt_query": "鬼滅 柱稽古編",
        "air_start": "2024-05-12",
        "air_end": "2024-06-30",
        "total_episodes": 8,
        "popularity_tier": "high",
    },
]

# Load existing catalog
with open(CATALOG_PATH, encoding="utf-8") as f:
    catalog = json.load(f)

existing_titles = {a["anime_title"] for a in catalog}
added = 0
for entry in NEW_ANIME:
    if entry["anime_title"] in existing_titles:
        print(f"[SKIP] {entry['anime_title']} — already in catalog")
        continue
    catalog.append(entry)
    added += 1
    print(f"[ADD] {entry['anime_title']} ({entry['anime_title_ja']})")

with open(CATALOG_PATH, "w", encoding="utf-8") as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)

print(f"\n=== 完了: {added}作品追加 / 合計{len(catalog)}作品 ===")
